[package]
name = "safetensors-testapp"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray-safetensors = {"path"= "../ndarray-safetensors", features=["unsafe_copy"]}
ndarray = "0.16.1"
safetensors = "0.5"
memmap2 = "0.9.5"
